export const ONE_LESSON_PRICE = {
	SINGLE_LESSON_PRICE: 65,
};
export const FIVE_LESSON_PRICE = {
	SINGLE_LESSON_PRICE: 60,
	TOTAL_PRICE: 300,
	SAVE: 25,
};
export const TEN_LESSON_PRICE = {
	SINGLE_LESSON_PRICE: 55,
	TOTAL_PRICE: 550,
	SAVE: 100,
};

export const BASIC_PACKAGE_PRICE = {
	TOTAL_PRICE: 695,
};

export const CORE_PACKAGE_PRICE = {
	TOTAL_PRICE: 845,
};

export const ROAD_TEST_PACKAGE_PRICE = 245;
